name: BackpackPlugin
main: com.otacon94.backplugin.BackpackPlugin
version: 1.0
author: Otacon94
commands:
   backpack:
     aliases: [bp]
     description: Store item inside your backpack. You will not drop it once dead.
permissions:
   backplugin.*:
     description: Gives access to all back commands
     children:
       backplugin.use: true
   backplugin.use:
     description: Allows you to use search command
     default: op